import { useEffect, useState } from "react";
import { Link, useParams } from "react-router-dom";
import { FileText } from "lucide-react";
import {
  Callout,
  InlineLoading,
  LinkButton,
  PageHeader,
} from "@/components/ui";
import {
  ApiError,
  api,
  inspectionImageUrl,
  inspectionReportUrl,
  type InspectionRecord,
} from "@/lib/api";
import { useAsyncTask } from "@/lib/hooks";
import { formatDateTime } from "@/lib/format";
import { CopilotPanel } from "./CopilotPanel";
import { Workspace } from "./inspection/InspectionView";
import { ResolutionPanel, productLabel } from "./records";

/** A saved inspection: whether MetrIQ resolved it from the photos, and all the evidence behind it. */
export function RecordView() {
  const { inspectionId = "" } = useParams();
  const load = useAsyncTask(api.getInspection);
  const [record, setRecord] = useState<InspectionRecord | null>(null);
  const [activeImageId, setActiveImageId] = useState<string | null>(null);
  const [selection, setSelection] = useState<string[]>([]);

  const { run } = load;
  useEffect(() => {
    setRecord(null);
    run(inspectionId)
      .then(setRecord)
      .catch(() => {});
  }, [inspectionId, run]);

  if (load.loading && !record) return <InlineLoading label={`Loading ${inspectionId}`} />;

  if (!record) {
    const err = load.error;
    const notFound = err instanceof ApiError && (err.status === 404 || err.status === 422);
    return (
      <div className="space-y-8 py-6">
        <PageHeader
          eyebrow="Saved inspection"
          title={notFound ? "Inspection not found" : "Inspection unavailable"}
          lead={
            notFound
              ? "No saved inspection matches this identifier."
              : err instanceof ApiError
                ? err.detail
                : "The inspection could not be loaded."
          }
        />
        <LinkButton to="/history" variant="secondary" size="lg">
          Back to history
        </LinkButton>
      </div>
    );
  }

  const analysis = record.analysis;
  const images = analysis.images;
  function selectRegions(ids: string[]) {
    setSelection(ids);
    const img = images.find((i) => i.ocr?.regions.some((r) => r.id === ids[0]));
    if (img) setActiveImageId(img.image_id);
  }

  return (
    <div className="space-y-8">
      <PageHeader
        eyebrow={`Saved inspection · ${record.inspection_id}`}
        title={productLabel(record)}
        lead={`Saved ${formatDateTime(record.created_at)} · ${record.image_count} ${record.image_count === 1 ? "photo" : "photos"}${record.standard_number ? ` · ${record.standard_number}` : ""}`}
        actions={
          <div className="flex flex-wrap items-center justify-end gap-4">
            <ReportButton inspectionId={record.inspection_id} />
            <Link
              to="/history"
              className="inline-flex items-center gap-1 font-mono text-[11px] uppercase tracking-[0.14em] text-accent hover:text-accent-hover"
            >
              All inspections
            </Link>
          </div>
        }
      />

      <ResolutionPanel
        required={record.escalation_required}
        reasons={record.escalation_reasons}
        selected={selection}
        onSelect={selectRegions}
      />

      <CopilotPanel
        inspectionId={record.inspection_id}
        hasHallmark={Boolean(analysis.hallmark?.detected)}
      />

      <Workspace
        result={analysis}
        urls={record.images.map((i) => inspectionImageUrl(i.url))}
        activeImageId={activeImageId ?? images[0].image_id}
        setActiveImageId={setActiveImageId}
        selectedRegion={selection[0] ?? null}
        setSelectedRegion={(id) => selectRegions(id ? [id] : [])}
        linkedRegions={selection}
        selectRegions={selectRegions}
        hideResolution
        hideCopilot
        savedInspectionId={record.inspection_id}
        intro={
          <Callout>
            <span className="font-medium">Saved evidence.</span> Everything below is the deterministic
            analysis stored when this inspection was saved — OCR regions on the stored photos,
            declarations, the identified product and the verified BIS standard, each with its
            source. Select a declaration or a region to see its OCR box on the photo. A saved record never
            changes.
          </Callout>
        }
      />
    </div>
  );
}

/* ---------------------------------------------------------------- report --- */

/** Opens the evidence-backed PDF report, generated by the backend from the stored record. */
function ReportButton({ inspectionId }: { inspectionId: string }) {
  return (
    <LinkButton to={inspectionReportUrl(inspectionId)} external variant="secondary" size="sm">
      <FileText className="h-3.5 w-3.5" />
      View report
    </LinkButton>
  );
}
